#DO NOT CHANGE THIS!!!
version: 2

#game language(can use: English, Czech, Chinese)
language: English

#server spawn
main_lobby:
  x: 0
  y: 0
  z: 0
  world: "world"

#players count, required to start
min_players: 4

#max player count
max_players: 12

#max game tam in seconds
max_game_time: 600

#every player is immediately teleported to the arena after join. (usefull for servers with bungeecord)
#direct_join: false

#starting cooldown in seconds
start_time: 30

#save players inventory on join?
save_inventory: true

#stats provider (yaml, json, mysql, sqlite) | set to 'none' if you dont want to save stats
stats_provider: none

#Chat format ( variables: {MESSAGE} {PLAYER} )
chat:
  game: "&7[&aGAME&7]&e&r {PLAYER} &3>&7 {MESSAGE}"
  spectator: "&7[&eSPECTATE&7]&e&r {PLAYER} &3>&7 {MESSAGE}"

reward:
  enable: false
  money: 0.0
  items: []
#Items example:
#
#  items:
#  - id: 0
#    damage: 0
#  - id: 245
#    damage: 0
#    name: "epic item"
#    lore: ["hi", "this is", "really cool item"]
#    enchants:
#    - id: 0
#      level: 4
