## example how to create new arena
---
#type of game classic/furious/stoned
type: "classic"
#material wool or clay
material: "wool"
#if enabled is false arena won´t load.
enabled: "false"
#signs
signs:
    join_sign_x: 89
    join_sign_y: 78
    join_sign_z: -487
    join_sign_world: "world"
    #enable status sign
    enable_status: "true"
    #status lines
    #variables:
    #   %alive = amount of in-game players
    #   %dead = amount of dead players
    #   %status = game status
    #   %type = type of arena
    #   %max = max players per arena
    status_line_1: "&3[CM 1]"
    status_line_2: "&a%alive/%max"
    status_line_3: "%status"
    status_line_4: "&6%type"
    #sign update every X seconds
    sign_update_time: 2
    #returns player to main level/lobby
    #world is same like arena_world
    return_sign_x: 566
    return_sign_y: 57
    return_sign_z: 890
#arena
arena:
    arena_world: "ColorMatch"
    #arena world
    join_position_x: 320
    join_position_y: 40
    join_position_z: 32
    #lobby is pregame lobby
    lobby_position_x: 344
    lobby_position_y: 102
    lobby_position_z: -982
    #corners of game floor place lava few blocks under floor
    first_corner_x: 300
    first_corner_z: 20
    #
    second_corner_x: 332
    second_corner_z: 52
    #
    floor_y: 50
    #
    spectator_mode: "true"
    #
    spec_spawn_x: 320
    spec_spawn_y: 50
    spec_spawn_z: 32
    #
    leave_position_x: 3455
    leave_position_y: 34
    leave_position_z: 450
    leave_position_world: "world"
    #time (seconds)
    max_game_time: 300
    #
    max_players: 10
    #
    min_players: 4
    #[seconds]
    starting_time: 30
    #[seconds]
    color_wait_time: 5
    #Arena finish message message levels example: world,cm,colormatch,lobby
    finish_msg_levels: "game"
    #enable time cycle - true / day / night / [ticks]
    time: "day"
    #Item reward for win put ID:DAMAGE:COUNT ->  17:5:1,17:4:9,4:0:1  
    #0 if you don´t want reward
    item_reward: 0
    #coin rewars put number of money
    money_reward: 0